[INFRASTRUCTURE] Add helm health check post-deploy test.

diff --git a/webapp/script/deploy b/webapp/script/deploy
--- a/webapp/script/deploy
+++ b/webapp/script/deploy
@@ -2,6 +2,7 @@
 
 cd "$(dirname "$0")/.."
 
+APP_NAME="wtrn-webapp"
 
 prompt_for_environment() {
   echo "Select the kubernetes environment:"
@@ -25,8 +26,16 @@ prompt_for_environment() {
 prompt_for_environment
 namespace=${ENVIRONMENT}
 
-helm upgrade --install  wtrn-webapp ./config/helm/ \
+helm upgrade --install ${APP_NAME} ./config/helm/ \
   --values ./config/helm/values.yaml \
   -f ./config/helm/values-${namespace}.yaml \
   --create-namespace \
   -n ${namespace}
+
+if ! helm test ${APP_NAME} -n ${namespace} 2>&1; then
+    echo "Test failed. This might be due to the application still starting up."
+    echo "The application might take a few minutes to be ready on first deployment."
+    echo "You can check the status with: kubectl get pods -n ${namespace}"
+    echo "And run the test again with: helm test ${APP_NAME} -n ${namespace}"
+    exit 1
+fi
